---
- name: Add secrets
  k8s:
    state: present
    force: True
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ namespace }}"
      stringData:
        "{{ item.stringData }}"
  with_items:
  - "{{ secrets }}"
  no_log: True